import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: {
    backgroundColor: '#f5f7f2',
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 18,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  eyebrow: {
    color: '#58705d',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 7,
  },
  title: {
    color: '#18352a',
    fontSize: 30,
    fontWeight: '800',
  },
  connectionBadge: {
    alignItems: 'center',
    backgroundColor: '#e8efe8',
    borderRadius: 16,
    flexDirection: 'row',
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  connectionDot: {
    backgroundColor: '#ba7b42',
    borderRadius: 4,
    height: 8,
    marginRight: 7,
    width: 8,
  },
  connectionText: {
    color: '#4d6653',
    fontSize: 12,
    fontWeight: '700',
  },
  statusPanel: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dfe7df',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: 18,
    padding: 16,
  },
  statusIcon: {
    alignItems: 'center',
    backgroundColor: '#edf3eb',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    marginRight: 12,
    width: 48,
  },
  statusIconText: {
    color: '#58705d',
    fontSize: 22,
  },
  statusCopy: {
    flex: 1,
  },
  statusTitle: {
    color: '#18352a',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 3,
  },
  statusDescription: {
    color: '#6a786d',
    fontSize: 13,
    lineHeight: 18,
  },
  cameraFrame: {
    backgroundColor: '#18352a',
    borderRadius: 12,
    height: 150,
    marginBottom: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  camera: {
    flex: 1,
  },
  cameraLiveBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(24, 53, 42, 0.8)',
    borderRadius: 14,
    flexDirection: 'row',
    left: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    position: 'absolute',
    top: 12,
  },
  cameraLiveDot: {
    backgroundColor: '#8bcf9d',
    borderRadius: 4,
    height: 8,
    marginRight: 6,
    width: 8,
  },
  cameraLiveText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  cameraPlaceholder: {
    alignItems: 'flex-start',
    backgroundColor: '#e8efe8',
    borderColor: '#cddccd',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  cameraTitle: {
    color: '#18352a',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  cameraDescription: {
    color: '#637267',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  cameraButton: {
    backgroundColor: '#18352a',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  cameraButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  confirmationBanner: {
    backgroundColor: '#fff3e7',
    borderColor: '#e5b37d',
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
  },
  confirmationTitle: {
    color: '#844618',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 3,
  },
  confirmationText: {
    color: '#925d33',
    fontSize: 13,
  },
  selectedBanner: {
    alignItems: 'center',
    backgroundColor: '#dcefe2',
    borderRadius: 10,
    flexDirection: 'row',
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  selectedLabel: {
    color: '#4f765b',
    fontSize: 12,
    fontWeight: '800',
    marginRight: 8,
    textTransform: 'uppercase',
  },
  selectedValue: {
    color: '#18352a',
    fontSize: 15,
    fontWeight: '800',
  },
  sectionHeading: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#18352a',
    fontSize: 18,
    fontWeight: '800',
  },
  sectionHint: {
    color: '#7b887e',
    fontSize: 12,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  actionCard: {
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    marginBottom: 12,
    minHeight: 102,
    padding: 16,
    width: '48.5%',
  },
  calmCard: {
    backgroundColor: '#ffffff',
    borderColor: '#d5e1d6',
  },
  warmCard: {
    backgroundColor: '#fff8ed',
    borderColor: '#ead7b9',
  },
  urgentCard: {
    backgroundColor: '#fff0ed',
    borderColor: '#e9b7ad',
  },
  selectedCard: {
    borderColor: '#326946',
    borderWidth: 2,
  },
  actionLabel: {
    color: '#18352a',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 6,
  },
  actionDescription: {
    color: '#68766c',
    fontSize: 12,
    lineHeight: 16,
  },
  footerText: {
    color: '#889289',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 'auto',
    paddingBottom: 12,
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.78,
  },
});
